### ISSUE TITLE
Failed to check status if repository starts with ssh://

### ISSUE THREAD

**Issue by SamVerschueren** [felipefdl/wercker-status#3]
Hi

I installed the plugin and added my username and password but it doesn't show the wercker status. Do I need to add or do something more? Do I need to set a setting in the wercker portal itself or should it work out of the box?

Thanks in advance!

**Comment by felipefdl** [comment]
Hi @SamVerschueren , here works well. I did remove all config and config again. So work well. You need check your user and password if is ok, after open git project folder (using wercker) in atom.

**Comment by SamVerschueren** [comment]
Hi @felipefdl 

I found the issue. My git url starts with ssh://git@bitbucket.org/username/repository.git. The ```git.coffee``` file only checks for urls that start with ```git@``` or ```https://```. I fixed it and now it works perfectly. I will add a pull request to fix this issue.

**Comment by felipefdl** [comment]
Awesome! Thanks.
